<template>
    <a-table :dataSource="selected" :columns="columns" bordered>
      <template #title>{{season}}</template>
      <template #honors="{ text: honors }">
      <span>
        <a-tag
          v-for="tag in honors"
          :key="tag"
          :color="tag === 'Championship' ? 'volcano' : ''"
        >
          {{ tag.toUpperCase() }}
        </a-tag>
      </span>
    </template>
    </a-table>
</template>

<script>
export default {
    name: 'Table',
    data() {
      return {
        selected: [],
        season: 0,
        dataSource: 
          {'LeBron_Wade_Bosh': {2010: [{'key': '1',
              'name': 'Lebron James',
              'age': 26,
              'salary': '$14,500,000 ',
              'pts': 26.7,
              'trb': 7.5,
              'ast': 7.0,
              'stl': 1.6,
              'blk': 0.6,
              'tov': 3.6,
              'honors': ["All-NBA 1st Team", "All-Defensive 1st Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Dwyane Wade',
              'age': 28,
              'salary': '$14,200,000 ',
              'pts': 25.5,
              'trb': 6.4,
              'ast': 4.6,
              'stl': 1.5,
              'blk': 1.1,
              'tov': 3.1,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Chris Bosh',
              'age': 26,
              'salary': '$14,500,000 ',
              'pts': 18.7,
              'trb': 8.3,
              'ast': 1.9,
              'stl': 0.8,
              'blk': 0.6,
              'tov': 1.8,
              'honors': ["All-Star"]
            }],
            2011: [{'key': '1',
              'name': 'Lebron James',
              'age': 27,
              'salary': '$16,022,500 ',
              'pts': 27.1,
              'trb': 7.9,
              'ast': 6.2,
              'stl': 1.9,
              'blk': 0.8,
              'tov': 3.4,
              'honors': ["Championship","All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "MVP", "FMVP"]
            },
             {'key': '2',
              'name': 'Dwyane Wade',
              'age': 29,
              'salary': '$15,691,000 ',
              'pts': 22.1,
              'trb': 4.8,
              'ast': 4.6,
              'stl': 1.7,
              'blk': 1.3,
              'tov': 2.6,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Chris Bosh',
              'age': 27,
              'salary': '$16,022,500 ',
              'pts': 18.0,
              'trb': 7.9,
              'ast': 1.8,
              'stl': 0.9,
              'blk': 0.8,
              'tov': 2.1,
              'honors': ["Championship", "All-Star"]
            }],
            2012: [{'key': '1',
              'name': 'Lebron James',
              'age': 28,
              'salary': '$17,545,000 ',
              'pts': 26.8,
              'trb': 8.0,
              'ast': 7.3,
              'stl': 1.7,
              'blk': 0.9,
              'tov': 3.0,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "MVP", "FMVP"]
            },
             {'key': '2',
              'name': 'Dwyane Wade',
              'age': 30,
              'salary': '$17,182,000 ',
              'pts': 21.2,
              'trb': 5.0,
              'ast': 5.1,
              'stl': 1.9,
              'blk': 0.8,
              'tov': 2.8,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Chris Bosh',
              'age': 28,
              'salary': '$17,545,000 ',
              'pts': 16.6,
              'trb': 6.8,
              'ast': 1.7,
              'stl': 0.9,
              'blk': 1.4,
              'tov': 1.7,
              'honors': ["Championship", "All-Star"]
            }],
            2013: [{'key': '1',
              'name': 'Lebron James',
              'age': 29,
              'salary': '$19,067,500 ',
              'pts': 27.1,
              'trb': 6.9,
              'ast': 6.3,
              'stl': 1.6,
              'blk': 0.3,
              'tov': 3.5,
              'honors': ["All-NBA 1st Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Dwyane Wade',
              'age': 31,
              'salary': '$18,673,000 ',
              'pts': 19.0,
              'trb': 4.5,
              'ast': 4.7,
              'stl': 1.5,
              'blk': 0.5,
              'tov': 3.0,
              'honors': ["All-Star"]
            },
             {'key': '3',
              'name': 'Chris Bosh',
              'age': 29,
              'salary': '$19,067,500 ',
              'pts': 16.2,
              'trb': 6.6,
              'ast': 1.1,
              'stl': 1.0,
              'blk': 1.0,
              'tov': 1.6,
              'honors': ["All-Star"]
            }]},
           'Pierce_Garnett_Allen': {2007: [{'key': '1',
              'name': 'Paul Pierce',
              'age': 30,
              'salary': '$16,360,094 ',
              'pts': 19.6,
              'trb': 5.1,
              'ast': 4.5,
              'stl': 1.3,
              'blk': 0.5,
              'tov': 2.8,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star", "FMVP"]
            },
             {'key': '2',
              'name': 'Kevin Garnett',
              'age': 31,
              'salary': '$23,750,000 ',
              'pts': 18.8,
              'trb': 9.2,
              'ast': 3.4,
              'stl': 1.4,
              'blk': 1.3,
              'tov': 1.9,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Ray Allen',
              'age': 32,
              'salary': '$16,000,000 ',
              'pts': 17.4,
              'trb': 3.7,
              'ast': 3.1,
              'stl': 0.9,
              'blk': 0.2,
              'tov': 1.7,
              'honors': ["Championship","All-Star"]
            }],
            2008: [{'key': '1',
              'name': 'Paul Pierce',
              'age': 31,
              'salary': '$18,077,903 ',
              'pts': 20.5,
              'trb': 5.6,
              'ast': 3.6,
              'stl': 1.0,
              'blk': 0.3,
              'tov': 2.8,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Kevin Garnett',
              'age': 32,
              'salary': '$24,751,934 ',
              'pts': 15.8,
              'trb': 8.5,
              'ast': 2.5,
              'stl': 1.1,
              'blk': 1.2,
              'tov': 1.6,
              'honors': ["All-Defensive 1st Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Ray Allen',
              'age': 33,
              'salary': '$18,388,430 ',
              'pts': 18.2,
              'trb': 3.5,
              'ast': 2.8,
              'stl': 0.9,
              'blk': 0.2,
              'tov': 1.7,
              'honors': ["All-Star"]
            }],
            2009: [{'key': '1',
              'name': 'Paul Pierce',
              'age': 32,
              'salary': '$19,795,712 ',
              'pts': 18.3,
              'trb': 4.4,
              'ast': 3.1,
              'stl': 1.2,
              'blk': 0.4,
              'tov': 2.3,
              'honors': ["All-Star"]
            },
             {'key': '2',
              'name': 'Kevin Garnett',
              'age': 33,
              'salary': '$16,400,000 ',
              'pts': 14.3,
              'trb': 7.3,
              'ast': 2.7,
              'stl': 1.0,
              'blk': 0.8,
              'tov': 1.5,
              'honors': ["All-Star"]
            },
             {'key': '3',
              'name': 'Ray Allen',
              'age': 34,
              'salary': '$18,776,860 ',
              'pts': 16.3,
              'trb': 3.2,
              'ast': 2.6,
              'stl': 0.8,
              'blk': 0.3,
              'tov': 1.6}],
            2010: [{'key': '1',
              'name': 'Paul Pierce',
              'age': 33,
              'salary': '$13,876,321 ',
              'pts': 18.9,
              'trb': 5.4,
              'ast': 3.3,
              'stl': 1.0,
              'blk': 0.6,
              'tov': 2.1,
              'honors': ["All-Star"]
            },
             {'key': '2',
              'name': 'Kevin Garnett',
              'age': 34,
              'salary': '$18,800,000 ',
              'pts': 14.9,
              'trb': 8.9,
              'ast': 2.4,
              'stl': 1.3,
              'blk': 0.8,
              'tov': 1.6,
              'honors': ["All-Defensive 1st Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Ray Allen',
              'age': 35,
              'salary': '$10,000,000 ',
              'pts': 16.5,
              'trb': 3.4,
              'ast': 2.7,
              'stl': 1.0,
              'blk': 0.2,
              'tov': 1.5,
              'honors': ["All-Star"]
            }],
            2011: [{'key': '1',
              'name': 'Paul Pierce',
              'age': 34,
              'salary': '$15,333,334 ',
              'pts': 19.4,
              'trb': 5.2,
              'ast': 4.5,
              'stl': 1.1,
              'blk': 0.4,
              'tov': 2.8,
              'honors': ["All-Star"]
            },
             {'key': '2',
              'name': 'Kevin Garnett',
              'age': 35,
              'salary': '$21,247,044 ',
              'pts': 15.8,
              'trb': 8.2,
              'ast': 2.9,
              'stl': 0.9,
              'blk': 1.0,
              'tov': 1.8,
              'honors': ["All-Defensive 2nd Team"]
            },
             {'key': '3',
              'name': 'Ray Allen',
              'age': 36,
              'salary': '$10,000,000 ',
              'pts': 14.2,
              'trb': 3.1,
              'ast': 2.4,
              'stl': 1.1,
              'blk': 0.2,
              'tov': 1.5}]},
           'Durant_Westbrook_Harden': {2009: [{'key': '1',
              'name': 'Kevin Durant',
              'age': 21,
              'salary': '$4,796,880 ',
              'pts': 26.0,
              'trb': 6.4,
              'ast': 5.9,
              'stl': 0.7,
              'blk': 1.1,
              'tov': 2.9,
              'honors': ["All-NBA 1st Team", "All-Star", "Scoring Leader"]
            },
             {'key': '2',
              'name': 'Russell Westbrook',
              'age': 21,
              'salary': '$3,755,640 ',
              'pts': 16.1,
              'trb': 4.9,
              'ast': 8.0,
              'stl': 1.3,
              'blk': 0.4,
              'tov': 3.3,
            },
             {'key': '3',
              'name': 'James Harden',
              'age': 20,
              'salary': '$4,054,160 ',
              'pts': 9.9,
              'trb': 3.2,
              'ast': 1.8,
              'stl': 1.1,
              'blk': 0.3,
              'tov': 1.4,
              'honors': ["All-Rookie 2nd Team"]
            }],
            2010: [{'key': '1',
              'name': 'Kevin Durant',
              'age': 22,
              'salary': '$6,053,663 ',
              'pts': 27.7,
              'trb': 6.8,
              'ast': 2.7,
              'stl': 1.1,
              'blk': 1.0,
              'tov': 2.8,
              'honors': ["All-NBA 1st Team", "All-Star", "Scoring Leader"]
            },
             {'key': '2',
              'name': 'Russell Westbrook',
              'age': 22,
              'salary': '$4,017,720 ',
              'pts': 21.9,
              'trb': 4.6,
              'ast': 8.2,
              'stl': 1.9,
              'blk': 0.4,
              'tov': 3.9,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'James Harden',
              'age': 21,
              'salary': '$4,304,520 ',
              'pts': 12.2,
              'trb': 3.1,
              'ast': 2.1,
              'stl': 1.1,
              'blk': 0.3,
              'tov': 1.3}],
            2011: [{'key': '1',
              'name': 'Kevin Durant',
              'age': 23,
              'salary': '$15,506,632 ',
              'pts': 28.0,
              'trb': 8.0,
              'ast': 3.5,
              'stl': 1.3,
              'blk': 1.2,
              'tov': 3.8,
              'honors': ["All-NBA 1st Team", "All-Star", "Scoring Learer", "AMVP"]
            },
             {'key': '2',
              'name': 'Russell Westbrook',
              'age': 23,
              'salary': '$5,082,416 ',
              'pts': 23.6,
              'trb': 4.6,
              'ast': 5.5,
              'stl': 1.7,
              'blk': 0.3,
              'tov': 3.6,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'James Harden',
              'age': 22,
              'salary': '$4,604,760 ',
              'pts': 16.8,
              'trb': 4.1,
              'ast': 3.7,
              'stl': 1.0,
              'blk': 0.2,
              'tov': 2.2,
              'honors': ["SMOY"]
            }]},
           'LeBron_Irving_Love': {2014: [{'key': '1',
              'name': 'Lebron James',
              'age': 30,
              'salary': '$20,644,400 ',
              'pts': 25.3,
              'trb': 6.0,
              'ast': 7.4,
              'stl': 1.6,
              'blk': 0.7,
              'tov': 3.9,
              'honors': ["All-NBA 1st Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Kyrie Irving',
              'age': 22,
              'salary': '$7,070,730 ',
              'pts': 21.7,
              'trb': 3.2,
              'ast': 5.2,
              'stl': 1.5,
              'blk': 0.3,
              'tov': 2.5,
              'honors': ["All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Kevin Love',
              'age': 26,
              'salary': '$15,719,062 ',
              'pts': 16.4,
              'trb': 9.7,
              'ast': 2.2,
              'stl': 0.7,
              'blk': 0.5,
              'tov': 1.6}],
            2015: [{'key': '1',
              'name': 'Lebron James',
              'age': 31,
              'salary': '$22,971,000 ',
              'pts': 25.3,
              'trb': 7.4,
              'ast': 6.8,
              'stl': 1.4,
              'blk': 0.6,
              'tov': 3.3,
              'honors': ["Championship", "All-NBA 1st Team", "All-Star", "FMVP"]
            },
             {'key': '2',
              'name': 'Kyrie Irving',
              'age': 23,
              'salary': '$14,746,000 ',
              'pts': 19.6,
              'trb': 3.0,
              'ast': 4.7,
              'stl': 1.1,
              'blk': 0.3,
              'tov': 2.3,
              'honors': ["Championship"]
            },
             {'key': '3',
              'name': 'Kevin Love',
              'age': 27,
              'salary': '$19,500,000 ',
              'pts': 16.0,
              'trb': 9.9,
              'ast': 2.4,
              'stl': 0.8,
              'blk': 0.5,
              'tov': 1.8,
              'honors': ["Championship"]
            }],
            2016: [{'key': '1',
              'name': 'Lebron James',
              'age': 32,
              'salary': '$30,963,450 ',
              'pts': 26.4,
              'trb': 8.6,
              'ast': 8.7,
              'stl': 1.2,
              'blk': 0.6,
              'tov': 4.1,
              'honors': ["All-NBA 1st Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Kyrie Irving',
              'age': 24,
              'salary': '$17,638,063 ',
              'pts': 25.2,
              'trb': 3.2,
              'ast': 5.8,
              'stl': 1.2,
              'blk': 0.3,
              'tov': 2.5,
              'honors': ["All-Star"]
            },
             {'key': '3',
              'name': 'Kevin Love',
              'age': 28,
              'salary': '$21,165,675 ',
              'pts': 19.0,
              'trb': 11.1,
              'ast': 1.9,
              'stl': 0.9,
              'blk': 0.4,
              'tov': 2.0,
              'honors': ["All-Star"]
            }]},
           'Curry_Thompson_Green': {
              2012: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 24,
              'salary': '$850,000 ',
              'pts': 22.9,
              'trb': 4.0,
              'ast': 6.9,
              'stl': 1.6,
              'blk': 0.2,
              'tov': 3.1,
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 22,
              'salary': '$2,286,000 ',
              'pts': 16.6,
              'trb': 3.7,
              'ast': 2.2,
              'stl': 1.0,
              'blk': 0.5,
              'tov': 1.9,
            },
             {'key': '3',
              'name': 'Draymond Green',
              'age': 22,
              'salary': '$915,243 ',
              'pts': 2.9,
              'trb': 3.3,
              'ast': 0.7,
              'stl': 0.5,
              'blk': 0.3,
              'tov': 0.6,
            }],
              2013: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 25,
              'salary': '$9,887,642 ',
              'pts': 24.0,
              'trb': 4.3,
              'ast': 8.5,
              'stl': 1.6,
              'blk': 0.2,
              'tov': 3.8,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 23,
              'salary': '$2,317,920 ',
              'pts': 18.4,
              'trb': 3.1,
              'ast': 2.2,
              'stl': 0.9,
              'blk': 0.5,
              'tov': 1.7,
            },
             {'key': '3',
              'name': 'Draymond Green',
              'age': 23,
              'salary': '$875,000 ',
              'pts': 6.2,
              'trb': 5.0,
              'ast': 1.9,
              'stl': 1.2,
              'blk': 0.9,
              'tov': 1.9,
            }],
            2014: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 26,
              'salary': '$10,629,213 ',
              'pts': 23.8,
              'trb': 4.3,
              'ast': 7.7,
              'stl': 2.0,
              'blk': 0.2,
              'tov': 3.1,
              'honors': ["Championship", "All-NBA 1st Team", "All-Star", "MVP"]
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 24,
              'salary': '$3,075,880 ',
              'pts': 21.7,
              'trb': 3.2,
              'ast': 2.9,
              'stl': 1.1,
              'blk': 0.8,
              'tov': 1.9,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Draymond Green',
              'age': 24,
              'salary': '$915,243 ',
              'pts': 11.7,
              'trb': 8.2,
              'ast': 3.7,
              'stl': 1.6,
              'blk': 1.3,
              'tov': 1.7,
              'honors': ["Championship", "All-Defensive 1st Team"]
            }],
            2015: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 27,
              'salary': '$11,370,786 ',
              'pts': 30.1,
              'trb': 5.4,
              'ast': 6.7,
              'stl': 2.1,
              'blk': 0.2,
              'tov': 2.0,
              'honors': ["All-NBA 1st Team", "All-Star", "MVP", "Scoring Leader", "Steals Leader"]
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 25,
              'salary': '$15,500,000 ',
              'pts': 22.1,
              'trb': 3.8,
              'ast': 2.1,
              'stl': 0.8,
              'blk': 0.6,
              'tov': 1.7,
              'honors': ["All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Draymond Green',
              'age': 25,
              'salary': '$14,300,000 ',
              'pts': 14.0,
              'trb': 9.5,
              'ast': 7.4,
              'stl': 1.5,
              'blk': 1.4,
              'tov': 3.2,
              'honors': ["All-NBA 2nd Team", "All-Defensive 1st Team", "All-Star"]
            }]},
           'Curry_Thompson_Durant': {2016: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 28,
              'salary': '$12,112,359 ',
              'pts': 25.3,
              'trb': 4.5,
              'ast': 6.6,
              'stl': 1.8,
              'blk': 0.2,
              'tov': 3.0,
              'honors': ["Championship", "All-NBA 2nd Team", "All-Star", "MVP"]
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 26,
              'salary': '$16,663,575 ',
              'pts': 22.3,
              'trb': 3.7,
              'ast': 2.1,
              'stl': 0.8,
              'blk': 0.5,
              'tov': 1.6,
              'honors': ["Championship", "All-Star"]
            },
             {'key': '3',
              'name': 'Kevin Durant',
              'age': 28,
              'salary': '$26,540,100 ',
              'pts': 25.1,
              'trb': 8.3,
              'ast': 4.8,
              'stl': 1.1,
              'blk': 1.6,
              'tov': 2.2,
              'honors': ["Championship","All-NBA 2nd Team", "All-Star", "FMVP"]
            }],
            2017: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 29,
              'salary': '$34,682,550 ',
              'pts': 26.4,
              'trb': 5.1,
              'ast': 6.1,
              'stl': 1.6,
              'blk': 0.2,
              'tov': 3.0,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star", "MVP"]
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 27,
              'salary': '$17,826,150 ',
              'pts': 20.0,
              'trb': 3.8,
              'ast': 2.5,
              'stl': 0.8,
              'blk': 0.5,
              'tov': 1.8,
              'honors': ["Championship", "All-Star"]
            },
             {'key': '3',
              'name': 'Kevin Durant',
              'age': 29,
              'salary': '$25,000,000 ',
              'pts': 26.4,
              'trb': 6.8,
              'ast': 5.4,
              'stl': 0.7,
              'blk': 1.8,
              'tov': 3.0,
              'honors': ["Championship", "All-NBA 1st Team", "All-Star", "FMVP"]
            }],
            2018: [{'key': '1',
              'name': 'Stephen Curry',
              'age': 30,
              'salary': '$37,457,154 ',
              'pts': 27.3,
              'trb': 5.3,
              'ast': 5.2,
              'stl': 1.3,
              'blk': 0.4,
              'tov': 2.8,
              'honors': ["Championship", "All-NBA 1st Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Klay Thompson',
              'age': 28,
              'salary': '$18,988,725 ',
              'pts': 21.5,
              'trb': 3.8,
              'ast': 2.4,
              'stl': 1.1,
              'blk': 0.6,
              'tov': 1.5,
              'honors': ["All-Star", "All-Defensive 2nd Team"]
            },
             {'key': '3',
              'name': 'Kevin Durant',
              'age': 30,
              'salary': '$30,000,000 ',
              'pts': 26.0,
              'trb': 6.4,
              'ast': 5.9,
              'stl': 0.7,
              'blk': 1.1,
              'tov': 2.8,
              'honors': ["All-NBA 2nd Team", "All-Star", "AMVP"]
            }]},
           'Kobe_Gasol_Bynum': {2008: [{'key': '1',
              'name': 'Kobe Bryant',
              'age': 30,
              'salary': '$21,262,500 ',
              'pts': 26.8,
              'trb': 5.2,
              'ast': 4.9,
              'stl': 1.5,
              'blk': 0.5,
              'tov': 2.6,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "AMVP","FMVP"]
            },
             {'key': '2',
              'name': 'Pau Gasol',
              'age': 28,
              'salary': '$15,106,000 ',
              'pts': 18.9,
              'trb': 9.6,
              'ast': 3.5,
              'stl': 0.6,
              'blk': 1.0,
              'tov': 1.9,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Andrew Bynum',
              'age': 21,
              'salary': '$2,769,300 ',
              'pts': 14.3,
              'trb': 8.0,
              'ast': 1.4,
              'stl': 0.4,
              'blk': 1.8,
              'tov': 1.7,
              'honors': ["Championship"]
            }],
            2009: [{'key': '1',
              'name': 'Kobe Bryant',
              'age': 31,
              'salary': '$23,034,375 ',
              'pts': 27.0,
              'trb': 5.4,
              'ast': 5.0,
              'stl': 1.5,
              'blk': 0.3,
              'tov': 3.2,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "FMVP"]
            },
             {'key': '2',
              'name': 'Pau Gasol',
              'age': 29,
              'salary': '$16,452,000 ',
              'pts': 18.3,
              'trb': 11.3,
              'ast': 3.4,
              'stl': 0.6,
              'blk': 1.7,
              'tov': 2.2,
              'honors': ["Championship", "All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Andrew Bynum',
              'age': 22,
              'salary': '$12,526,998 ',
              'pts': 15.0,
              'trb': 8.3,
              'ast': 1.0,
              'stl': 0.5,
              'blk': 1.4,
              'tov': 1.8,
              'honors': ["Championship"]
            }],
            2010: [{'key': '1',
              'name': 'Kobe Bryant',
              'age': 32,
              'salary': '$24,806,250 ',
              'pts': 25.3,
              'trb': 5.1,
              'ast': 4.7,
              'stl': 1.2,
              'blk': 0.1,
              'tov': 3.0,
              'honors': ["All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "AMVP"]
            },
             {'key': '2',
              'name': 'Pau Gasol',
              'age': 30,
              'salary': '$17,823,000 ',
              'pts': 18.8,
              'trb': 10.2,
              'ast': 3.3,
              'stl': 0.6,
              'blk': 1.6,
              'tov': 1.7,
              'honors': [ "All-NBA 2nd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Andrew Bynum',
              'age': 23,
              'salary': '$13,700,000 ',
              'pts': 11.3,
              'trb': 9.4,
              'ast': 1.4,
              'stl': 0.4,
              'blk': 2.0,
              'tov': 1.4}],
            2011: [{'key': '1',
              'name': 'Kobe Bryant',
              'age': 33,
              'salary': '$25,244,493 ',
              'pts': 27.9,
              'trb': 5.4,
              'ast': 4.6,
              'stl': 1.2,
              'blk': 0.3,
              'tov': 3.5,
              'honors': ["All-NBA 1st Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Pau Gasol',
              'age': 31,
              'salary': '$18,714,150 ',
              'pts': 17.4,
              'trb': 10.4,
              'ast': 3.6,
              'stl': 0.6,
              'blk': 1.4,
              'tov': 2.2},
             {'key': '3',
              'name': 'Andrew Bynum',
              'age': 24,
              'salary': '$14,900,000 ',
              'pts': 18.7,
              'trb': 11.8,
              'ast': 1.4,
              'stl': 0.5,
              'blk': 1.9,
              'tov': 2.5,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            }]},
           'Duncan_Parker_Ginobili': {
            2002: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 26,
              'salary': '$12,072,500 ',
              'pts': 23.3,
              'trb': 12.9,
              'ast': 3.9,
              'stl': 0.7,
              'blk': 2.9,
              'tov': 3.1,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "MVP", "FMVP"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 20,
              'salary': '$800,400 ',
              'pts': 15.5,
              'trb': 2.6,
              'ast': 5.3,
              'stl': 0.9,
              'blk': 0.1,
              'tov': 1.4,
              'honors': ["Championship"]
            },
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 25,
              'salary': '$1,325,000 ',
              'pts': 7.6,
              'trb': 2.3,
              'ast': 2.0,
              'stl': 1.4,
              'blk': 0.2,
              'tov': 1.2,
              'honors': ["Championship","All-Rookie 2nd Team"]
            }],
            2003: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 27,
              'salary': '$12,676,125 ',
              'pts': 22.3,
              'trb': 12.4,
              'ast': 3.1,
              'stl': 0.9,
              'blk': 2.7,
              'tov': 2.7,
              'honors': ["All-NBA 1st Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 21,
              'salary': '$856,200 ',
              'pts': 14.7,
              'trb': 3.2,
              'ast': 5.5,
              'stl': 0.8,
              'blk': 0.1,
              'tov': 2.4},
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 26,
              'salary': '$1,457,500 ',
              'pts': 12.8,
              'trb': 4.5,
              'ast': 1.9,
              'stl': 1.0,
              'blk': 0.4,
              'tov': 1.2,}],
            2004: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 28,
              'salary': '$14,260,641 ',
              'pts': 20.3,
              'trb': 11.1,
              'ast': 2.7,
              'stl': 0.7,
              'blk': 2.6,
              'tov': 1.9,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "FMVP"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 22,
              'salary': '$1,545,441 ',
              'pts': 16.6,
              'trb': 3.7,
              'ast': 6.1,
              'stl': 1.2,
              'blk': 0.1,
              'tov': 2.7,
              'honors': ["Championship"]
            },
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 27,
              'salary': '$6,603,500 ',
              'pts': 16.0,
              'trb': 4.4,
              'ast': 3.9,
              'stl': 1.6,
              'blk': 0.4,
              'tov': 2.3,
              'honors': ["Championship", "All-Star"]
            }],
            2005: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 29,
              'salary': '$15,845,156 ',
              'pts': 18.6,
              'trb': 11.0,
              'ast': 3.2,
              'stl': 0.9,
              'blk': 2.0,
              'tov': 2.5,
              'honors': ["All-NBA 2nd Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 23,
              'salary': '$8,400,000 ',
              'pts': 18.9,
              'trb': 3.3,
              'ast': 5.8,
              'stl': 1.0,
              'blk': 0.1,
              'tov': 3.1,
              'honors': ["All-Star"]
            },
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 28,
              'salary': '$7,428,937 ',
              'pts': 15.1,
              'trb': 3.5,
              'ast': 3.6,
              'stl': 1.6,
              'blk': 0.4,
              'tov': 1.9}],
            2006: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 30,
              'salary': '$17,429,672 ',
              'pts': 20.0,
              'trb': 10.6,
              'ast': 3.4,
              'stl': 0.8,
              'blk': 2.4,
              'tov': 2.8,
              'honors': ["Championship", "All-NBA 1st Team", "All-Defensive 1st Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 24,
              'salary': '$9,450,000 ',
              'pts': 18.6,
              'trb': 3.2,
              'ast': 5.5,
              'stl': 1.1,
              'blk': 0.1,
              'tov': 2.5,
              'honors': ["Championship", "All-Star", "FMVP"]
            },
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 29,
              'salary': '$8,254,375 ',
              'pts': 16.5,
              'trb': 4.4,
              'ast': 3.5,
              'stl': 1.5,
              'blk': 0.4,
              'tov': 2.1,
              'honors': ["Championship"]
            }],
            2007: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 31,
              'salary': '$19,014,188 ',
              'pts': 19.3,
              'trb': 11.3,
              'ast': 2.8,
              'stl': 0.7,
              'blk': 1.9,
              'tov': 2.3,
              'honors': [ "All-NBA 1st Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 25,
              'salary': '$10,500,000 ',
              'pts': 18.8,
              'trb': 3.2,
              'ast': 6.0,
              'stl': 0.8,
              'blk': 0.1,
              'tov': 2.4},
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 30,
              'salary': '$9,079,811 ',
              'pts': 19.5,
              'trb': 4.8,
              'ast': 4.5,
              'stl': 1.5,
              'blk': 0.4,
              'tov': 2.7,
              'honors': ["SMOY", "All-NBA 3rd Team"]
            }],
            2008: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 32,
              'salary': '$20,598,704 ',
              'pts': 19.3,
              'trb': 10.7,
              'ast': 3.5,
              'stl': 0.5,
              'blk': 1.7,
              'tov': 2.2,
              'honors': ["All-NBA 2nd Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 26,
              'salary': '$11,550,000 ',
              'pts': 22.0,
              'trb': 3.1,
              'ast': 6.9,
              'stl': 0.9,
              'blk': 0.1,
              'tov': 2.6,
              'honors': [ "All-NBA 3rd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 31,
              'salary': '$9,905,248 ',
              'pts': 15.5,
              'trb': 4.5,
              'ast': 3.6,
              'stl': 1.5,
              'blk': 0.4,
              'tov': 2.0}],
            2009: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 33,
              'salary': '$22,183,220 ',
              'pts': 17.9,
              'trb': 10.1,
              'ast': 3.2,
              'stl': 0.6,
              'blk': 1.5,
              'tov': 1.8,
              'honors': ["All-NBA 3rd Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 27,
              'salary': '$12,600,000 ',
              'pts': 16.0,
              'trb': 2.4,
              'ast': 5.7,
              'stl': 0.5,
              'blk': 0.1,
              'tov': 2.7},
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 32,
              'salary': '$10,728,130 ',
              'pts': 16.5,
              'trb': 3.8,
              'ast': 4.9,
              'stl': 1.4,
              'blk': 0.3,
              'tov': 2.1}],
            2010: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 34,
              'salary': '$18,700,000 ',
              'pts': 13.4,
              'trb': 8.9,
              'ast': 2.7,
              'stl': 0.7,
              'blk': 1.9,
              'tov': 1.6,
              'honors': ["All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 28,
              'salary': '$13,500,000 ',
              'pts': 17.5,
              'trb': 3.1,
              'ast': 6.6,
              'stl': 1.2,
              'blk': 0.1,
              'tov': 2.6,},
             {'key': '3',
              'name': 'Manu Ginobili',
              'age': 33,
              'salary': '$11,854,584 ',
              'pts': 17.4,
              'trb': 3.7,
              'ast': 4.9,
              'stl': 1.5,
              'blk': 0.4,
              'tov': 2.2,
              'honors': ["All-Star", "All-NBA 1st Team"]
            }]},
           'Duncan_Parker_Kawhi': {2012: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 36,
              'salary': '$9,638,554 ',
              'pts': 17.8,
              'trb': 9.9,
              'ast': 2.7,
              'stl': 0.7,
              'blk': 2.7,
              'tov': 2.1,
              'honors': ["All-NBA 1st Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 30,
              'salary': '$12,500,000 ',
              'pts': 20.3,
              'trb': 3.0,
              'ast': 7.6,
              'stl': 0.8,
              'blk': 0.1,
              'tov': 2.6,
              'honors': [ "All-NBA 2nd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Kawhi Leonard',
              'age': 21,
              'salary': '$1,861,920 ',
              'pts': 11.9,
              'trb': 6.0,
              'ast': 1.6,
              'stl': 1.7,
              'blk': 0.6,
              'tov': 1.1}],
            2013: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 37,
              'salary': '$10,361,446 ',
              'pts': 15.1,
              'trb': 9.7,
              'ast': 3.0,
              'stl': 0.6,
              'blk': 1.9,
              'tov': 2.1,
              'honors': ["Championship"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 31,
              'salary': '$12,500,000 ',
              'pts': 16.7,
              'trb': 2.3,
              'ast': 5.7,
              'stl': 0.5,
              'blk': 0.1,
              'tov': 2.2,
              'honors': ["Championship", "All-NBA 2nd Team", "All-Star"]
            },
             {'key': '3',
              'name': 'Kawhi Leonard',
              'age': 22,
              'salary': '$1,887,840 ',
              'pts': 12.8,
              'trb': 6.2,
              'ast': 2.0,
              'stl': 1.7,
              'blk': 0.8,
              'tov': 1.2,
              'honors': ["Championship", "All-Defensive 2nd Team", "FMVP"]
            }],
            2014: [{'key': '1',
              'name': 'Tim Duncan',
              'age': 38,
              'salary': '$10,000,000 ',
              'pts': 13.9,
              'trb': 9.1,
              'ast': 3.0,
              'stl': 0.8,
              'blk': 2.0,
              'tov': 1.7,
              'honors': ["All-NBA 3rd Team", "All-Defensive 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Tony Parker',
              'age': 32,
              'salary': '$12,500,000 ',
              'pts': 14.4,
              'trb': 1.9,
              'ast': 4.9,
              'stl': 0.6,
              'blk': 0.1,
              'tov': 2.1},
             {'key': '3',
              'name': 'Kawhi Leonard',
              'age': 23,
              'salary': '$2,894,059 ',
              'pts': 16.5,
              'trb': 7.2,
              'ast': 2.5,
              'stl': 2.3,
              'blk': 0.8,
              'tov': 1.5,
              'honors': ["All-Defensive 1st Team", "DPOY", "Steals Leader"]
            }]},
           'Paul_Griffin_Jordan': {
            2011: [{'key': '1',
              'name': 'Blake Griffin',
              'age': 22,
              'salary': '$7,226,892 ',
              'pts': 20.7,
              'trb': 10.9,
              'ast': 3.2,
              'stl': 0.8,
              'blk': 0.7,
              'tov': 2.3,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Chris Paul',
              'age': 26,
              'salary': '$17,779,458 ',
              'pts': 19.8,
              'trb': 3.6,
              'ast': 9.1,
              'stl': 2.5,
              'blk': 0.1,
              'tov': 2.1,
              'honors': ["All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "Steals Leader"]
            },
             {'key': '3',
              'name': 'DeAndre Jordan',
              'age': 23,
              'salary': '$10,532,977 ',
              'pts': 7.4,
              'trb': 8.3,
              'ast': 0.3,
              'stl': 0.5,
              'blk': 2.0,
              'tov': 1.1}],
            2012: [{'key': '1',
              'name': 'Blake Griffin',
              'age': 23,
              'salary': '$7,226,892 ',
              'pts': 18.0,
              'trb': 8.3,
              'ast': 3.7,
              'stl': 1.2,
              'blk': 0.6,
              'tov': 2.3,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Chris Paul',
              'age': 27,
              'salary': '$17,779,458 ',
              'pts': 16.9,
              'trb': 3.7,
              'ast': 9.7,
              'stl': 2.4,
              'blk': 0.1,
              'tov': 2.3,
              'honors': ["All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "AMVP", "Steals Leader"]
            },
             {'key': '3',
              'name': 'DeAndre Jordan',
              'age': 24,
              'salary': '$10,532,977 ',
              'pts': 8.8,
              'trb': 7.2,
              'ast': 0.3,
              'stl': 0.6,
              'blk': 1.4,
              'tov': 1.2}],
            2013: [{'key': '1',
              'name': 'Blake Griffin',
              'age': 24,
              'salary': '$16,441,500 ',
              'pts': 24.1,
              'trb': 9.5,
              'ast': 3.9,
              'stl': 1.2,
              'blk': 0.6,
              'tov': 2.8,
              'honors': ["All-NBA 2nd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Chris Paul',
              'age': 28,
              'salary': '$18,668,431 ',
              'pts': 19.1,
              'trb': 4.3,
              'ast': 10.7,
              'stl': 2.5,
              'blk': 0.1,
              'tov': 2.3,
              'honors': ["All-NBA 1st Team", "All-Defensive 1st Team", "All-Star", "Assists Leader", "Steals Leader"]
            },
             {'key': '3',
              'name': 'DeAndre Jordan',
              'age': 25,
              'salary': '$10,986,550 ',
              'pts': 10.4,
              'trb': 13.6,
              'ast': 0.9,
              'stl': 1.0,
              'blk': 2.5,
              'tov': 1.5,
              'honors': ["Rebounds Leader"]
            }],
            2014: [{'key': '1',
              'name': 'Blake Griffin',
              'age': 25,
              'salary': '$17,674,612 ',
              'pts': 21.9,
              'trb': 7.6,
              'ast': 5.3,
              'stl': 0.9,
              'blk': 0.5,
              'tov': 2.3,
              'honors': ["All-NBA 3rd Team", "All-Star"]
            },
             {'key': '2',
              'name': 'Chris Paul',
              'age': 29,
              'salary': '$20,068,563 ',
              'pts': 19.1,
              'trb': 4.6,
              'ast': 10.2,
              'stl': 1.9,
              'blk': 0.2,
              'tov': 2.3,
              'honors': ["All-NBA 2nd Team", "All-Defensive 1st Team", "All-Star", "Assists Leader"]
            },
             {'key': '3',
              'name': 'DeAndre Jordan',
              'age': 26,
              'salary': '$11,440,124 ',
              'pts': 11.5,
              'trb': 15.0,
              'ast': 0.7,
              'stl': 1.0,
              'blk': 2.2,
              'tov': 1.3,
              'honors': ["All-NBA 3rd Team", "All-Defensive 1st Team", "Rebounds Leader"]
            }],
            2016: [{'key': '1',
              'name': 'Blake Griffin',
              'age': 27,
              'salary': '$20,140,838 ',
              'pts': 21.6,
              'trb': 8.1,
              'ast': 4.9,
              'stl': 0.9,
              'blk': 0.4,
              'tov': 2.3},
             {'key': '2',
              'name': 'Chris Paul',
              'age': 31,
              'salary': '$22,868,827 ',
              'pts': 18.1,
              'trb': 5.0,
              'ast': 9.2,
              'stl': 2.0,
              'blk': 0.1,
              'tov': 2.4,
              'honors': ["All-Defensive 1st Team"]
            },
             {'key': '3',
              'name': 'DeAndre Jordan',
              'age': 28,
              'salary': '$21,165,675 ',
              'pts': 12.7,
              'trb': 13.8,
              'ast': 1.2,
              'stl': 0.6,
              'blk': 1.7,
              'tov': 1.4,
              'honors': ["All-NBA 3rd Team", "All-Star"]
            }]}},
        columns: [
          {
            title: "Name",
            dataIndex: 'name',
            key: 'name',
          },
          {
            title: 'Age',
            dataIndex: 'age',
            key: 'age',
          },
          {
            title: 'Salary',
            dataIndex: 'salary',
            key: 'salary',
          },
          {
            title: 'Points',
            dataIndex: 'pts',
            key: 'pts',
          },
          {
            title: 'Rebounds',
            dataIndex: 'trb',
            key: 'trb',
          },
          {
            title: 'Assists',
            dataIndex: 'ast',
            key: 'ast',
          },
          {
            title: 'Steals',
            dataIndex: 'stl',
            key: 'stl',
          },
          {
            title: 'Blocks',
            dataIndex: 'blk',
            key: 'blk',
          },
          {
            title: 'Turnovers',
            dataIndex: 'tov',
            key: 'tov',
          },
          {
            title: 'Honors',
            key: 'honors',
            dataIndex: 'honors',
            slots: { customRender: 'honors' },
          },

        ],
      }
    },
  
    mounted: function() {
      this.season = "Season: " + this.$route.query.season + "~" + (parseInt(this.$route.query.season) + 1);
      this.selected = this.dataSource[this.$route.query.name][this.$route.query.season];
    },
  
    methods: {
    }, 
}
</script>

